- name: Demo on load file
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

    - name: Load Universe file
        ansible.builtin.include_tasks:
          file: Universe.yml