#How to load another file

- name: Demo on load another file
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

    - name: Load another file
      ansible.builtin.include_task:
        file: Universe.yml
